// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4_y-sPqw1rQbq6BbzW5zI7o0zIwGxClE',
    appId: '1:208590462719:web:3562c3e711b6f14f2e36ca',
    messagingSenderId: '208590462719',
    projectId: 'medical-jp',
    authDomain: 'medical-jp.firebaseapp.com',
    storageBucket: 'medical-jp.appspot.com',
    measurementId: 'G-CV72D4Z967',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhF80KphQjqkxJMb9j5AUmmDJG_Dkjkw0',
    appId: '1:208590462719:android:0ad69fe80427a9bc2e36ca',
    messagingSenderId: '208590462719',
    projectId: 'medical-jp',
    storageBucket: 'medical-jp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvMkqHF8oGyi0yjptwaz4fRq3VWlUbIEU',
    appId: '1:208590462719:ios:d71d08a4893c6c582e36ca',
    messagingSenderId: '208590462719',
    projectId: 'medical-jp',
    storageBucket: 'medical-jp.appspot.com',
    iosBundleId: 'com.abd.medicaljp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4_y-sPqw1rQbq6BbzW5zI7o0zIwGxClE',
    appId: '1:208590462719:web:a3b3046de5ca5cba2e36ca',
    messagingSenderId: '208590462719',
    projectId: 'medical-jp',
    authDomain: 'medical-jp.firebaseapp.com',
    storageBucket: 'medical-jp.appspot.com',
    measurementId: 'G-E757VRQFVZ',
  );
}
